name: freshly_delivered_app
description: Freshly delivered app is an application that allows you to shop for preselected recipes easily using your smartphones.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  easy_debounce: ^2.0.3
  email_validator: ^2.1.17
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  # font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  input_history_text_field: ^0.2.0
  json_annotation: ^4.8.1
  loader_overlay: ^2.3.0
  multiple_result: ^5.1.0
  mockito: ^5.4.2
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  vector_graphics: ^1.1.7
  cached_network_image: ^3.2.3
  auto_size_text: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  cloud_firestore: ^4.8.4
  sqflite: ^2.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  custom_lint:
  firebase_auth_mocks: ^0.12.0
  flutter_lints: ^2.0.2
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
  sqflite_common_ffi: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  # background_image: "assets/background/background.jpg"
  color: "#ffffff"
  image: "assets/images/logo2.png"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
